### ISSUE TITLE
Error when viewing the module, content covering the letters, Magento 2 Porto Theme installed

### ISSUE THREAD

**Issue by Patric-Oliveira** [magepow/magento-2-shop-by-brand#2]
[](url)
![Screenshot from 2022-04-13 10-52-34](https://user-images.githubusercontent.com/82215275/163197670-88c7d2a4-5d15-4ca0-845c-42429d4b8c3b.png)

Hello, I'm a module user, I have this problem integrated with Porto Theme, could you tell me the necessary steps to solve this problem? what part of the code should i modify?

**Comment by magiccart** [comment]
Hi, The issue related to style is not a bug. If you need a custom style for the custom job you can create a ticket here https://magepow.com/ticket our developer will help you custom it.
Best regards,
